project_token: <insert project token>
name: simple-pipeline-demo
jobs:
    - job_id: < create and insert job id for data_ingest.py here>
      name: data_ingest
      language: python
      entrypoint: data_ingest.py


    - job_id: < create and insert job id for generate_report.py here>
      name: generate_report
      language: python
      entrypoint: generate_report.py
      dependencies: [ <insert job id for data_ingest.py here > ]